
sh /${REDIS_NODE_VOL_SH_NAME}/${REDIS_NODE_FIX_IP_SH_FILENAME} || { exit 1; };

sh /${REDIS_NODE_VOL_SH_NAME}/${REDIS_NODE_CLUSTER_OP_SH_FILENAME} || { exit 1; };

echo ${REDIS_NODE_READINESS_FILENAME} >> /data/${REDIS_NODE_SH_LOG_FILENAME} || { exit 1; };
echo >> ${REDIS_NODE_READINESS_FILENAME} || { exit 1; };
