---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ namespace }}
  name: {{ webhook_service }}
  labels:
    app: {{ webhook_label }}
spec:
  type: ClusterIP
  ports:
  - name: https
    protocol: TCP
    port: {{ webhook_port }}
    targetPort: {{ webhook_port }}
  selector:
    app: {{ webhook_label }}
